apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jupyterhub.yaml
  - monitoring.yaml
  - superset.yaml
  - argo.yaml
  - datacatalog.yaml
  - dashboard.yaml
  - kafka.yaml
  - observatorium.yaml
