apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cluster-management
  - argocd-projects.yaml
patchesStrategicMerge:
  - ceph.yaml
  - cluster-resources.yaml
  - kubevirt-hyperconverged.yaml
  - local-storage.yaml
