apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-operator.yaml
  - auth.yaml
  - ci-prow-test-pods.yaml
  - ci-prow.yaml
  - cluster-logging.yaml
  - jh-idle-culler.yaml
  - kubeflow.yaml
  - observatorium-operator.yaml
  - observatorium.yaml
  - odh-operator.yaml
  - prod-aicoe-ci.yaml
  - slack-first.yaml
  - vector.yaml
