apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo.yaml
  - ci-prow.yaml
  - cluster-logging.yaml
  - dashboard.yaml
  - datacatalog.yaml
  - jupyterhub.yaml
  - kafka.yaml
  - kfdefs.yaml
  - monitoring.yaml
  - observatorium.yaml
  - observatorium-operator.yaml
  - prod-aicoe-ci.yaml
  - superset.yaml
  - kubeflow.yaml
