apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertreceiver.yaml
  - ceph.yaml
  - cluster-resources.yaml
  - kubevirt-hyperconverged.yaml
  - local-storage.yaml

nameSuffix: -zero
