apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acm.yaml
  - alertreceiver.yaml
  - argocd-projects.yaml
  - cluster-resources.yaml
  - kubevirt-hyperconverged.yaml

nameSuffix: -infra
